perl ../tv16.check_avs.pl ./all.OK.P.videoFeatureExtractionResults.xml
perl ../tv16.check_avs.pl ./empty.desc.P.videoFeatureExtractionResults.xml
perl ../tv16.check_avs.pl ./empty.pid.P.videoFeatureExtractionResults.xml
perl ../tv16.check_avs.pl ./empty.seq.P.videoFeatureExtractionResults.xml
perl ../tv16.check_avs.pl ./empty.shotid.P.videoFeatureExtractionResults.xml
perl ../tv16.check_avs.pl ./empty.time.P.videoFeatureExtractionResults.xml
perl ../tv16.check_avs.pl ./wrong.shotID.P.videoFeatureExtractionResults.xml
perl ../tv16.check_avs.pl ./wrong.topic.P.videoFeatureExtractionResults.xml
perl ../tv16.check_avs.pl ./wrong.xml.P.videoFeatureExtractionResults.xml
