"""
Django settings for evalbase project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
    'huey.contrib.djhuey',
    'pinax.announcements',
    'csvexport',
    'evalbase.templatetags.get_fields',
    'django_select2',
    'django_cleanup.apps.CleanupConfig',
    'evalbase',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'evalbase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates') ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'eb_tags': 'evalbase.templatetags.eb_tags',
                'csp': 'csp.templatetags.csp'
            }
        },
    },
]

WSGI_APPLICATION = 'evalbase.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_ROOT = BASE_DIR / 'static'
STATIC_URL = '/static/'
#STATICFILES_DIRS = [
#    Path(BASE_DIR) / "static",
#]

# Email setup
# for deployment:
# EMAIL_HOST = 'smtp.nist.gov'
#
# for development:
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = Path(BASE_DIR) / 'sent_emails'

# Login redirect
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CHECK_SCRIPT_PATH = Path(BASE_DIR) / 'checkers'

# Bootstrap5 config
BOOTSTRAP5 = {
    'set_placeholder': False
}

# Huey config
HUEY = {
    'huey_class': 'huey.SqliteHuey',
    'name': 'evalbase-tasks',
    'filename': DATABASES['default']['NAME'],
    'results': True,
    'store_none': False,
    'immediate': False,
    'utc': False,
    'fsync': False,
    'cache_mb': 64,
    'consumer': {
        'workers': 1,
        'worker_type': 'greenlet',
        'initial_delay': 0.1,
        'backoff': 1.15,
        'max_delay': 10.0,
        'scheduler_interval': 1,
        'periodic': False,
        'check_worker_health': True,
        'health_check_interval': 1,
    },
}

# django-csp Content Security Policy
# https://django-csp.readthedocs.io/en/latest/configuration.html
# https://www.w3.org/TR/CSP/#csp-directives

CSP_DEFAULT_SRC = ("'self'")
CSP_SCRIPT_SRC = ("'self'", 'cdn.jsdelivr.net', "'unsafe-inline'")
CSP_SCRIPT_SRC_ATTR = ("'unsafe-inline'")
CSP_OBJECT_SRC = ("'self'")
CSP_STYLE_SRC = ("'self'", 'cdn.jsdelivr.net')
# CSP_INCLUDE_NONCE_IN = ['script-src', 'script-src-attr']

# Have CSRF cookies use SameSite: Strict
CSRF_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_SECURE = False

# CSVexport
CSV_EXPORT_REFERENCE_DEPTH = 3
CSV_EXPORT_EMPTY_VALUE = ''
