# Generated by Django 2.2.4 on 2019-08-28 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=15)),
                ('longname', models.CharField(max_length=50)),
                ('open_signup', models.BooleanField()),
                ('tech_contact', models.EmailField(max_length=254)),
                ('admin_contact', models.EmailField(max_length=254)),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=150)),
                ('city_state', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(help_text='A short (max 15 chars) acronym or abbreviation.', max_length=15, verbose_name='Short name')),
                ('longname', models.CharField(help_text='The full name of your organization.', max_length=50, verbose_name='Long name')),
                ('passphrase', models.CharField(editable=False, max_length=20)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evalbase.Conference')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_contact_for', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='member_of', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_owner_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
