# Generated by Django 3.0 on 2019-12-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evalbase.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_template', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=15)),
                ('longname', models.CharField(max_length=50)),
                ('required', models.BooleanField()),
                ('task_open', models.BooleanField()),
                ('has_file', models.BooleanField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evalbase.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=15)),
                ('value', models.CharField(max_length=250)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evalbase.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('meta_key', models.CharField(max_length=15)),
                ('sequence', models.IntegerField()),
                ('submit_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evalbase.SubmitForm')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='submitform',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evalbase.Task'),
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evalbase.Task'),
        ),
    ]
