# Generated by Django 3.0 on 2019-12-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0002_auto_20191202_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitformfield',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Number'), (3, 'Radio'), (4, 'Checkbox'), (5, 'Email'), (6, 'Comment'), (7, 'Runtag')], default=1),
        ),
    ]
