# Generated by Django 3.0 on 2019-12-10 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import evalbase.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evalbase', '0004_submitformfield_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='has_file',
        ),
        migrations.AddField(
            model_name='conference',
            name='results_root',
            field=models.CharField(default='<django.db.models.fields.CharField>/runs', max_length=15),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(default='', upload_to=evalbase.models.get_submission_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitformfield',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Number'), (3, 'Radio'), (4, 'Checkbox'), (5, 'Email'), (6, 'Comment'), (7, 'Runtag'), (8, 'Org')], default=1),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('template', models.CharField(max_length=30)),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evalbase.Signature')),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='agreements',
            field=models.ManyToManyField(to='evalbase.Agreement'),
        ),
    ]
