# Generated by Django 3.0 on 2019-12-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0005_auto_20191210_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitformfield',
            name='submit_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evalbase.SubmitForm'),
        ),
    ]
