# Generated by Django 3.0 on 2019-12-11 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evalbase', '0006_auto_20191211_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='agreements',
            field=models.ManyToManyField(blank=True, to='evalbase.Agreement'),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='header_template',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalbase.Task'),
        ),
        migrations.AlterField(
            model_name='submitformfield',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Number'), (3, 'Radio'), (4, 'Checkbox'), (5, 'Email'), (6, 'Comment'), (7, 'Runtag'), (8, 'Yesno')], default=1),
        ),
        migrations.AlterField(
            model_name='submitformfield',
            name='submit_form',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='evalbase.SubmitForm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
