# Generated by Django 3.0 on 2019-12-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0007_auto_20191211_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='runtag',
            field=models.CharField(default='foo', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitmeta',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalbase.Submission'),
        ),
    ]
