# Generated by Django 3.0 on 2019-12-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0008_auto_20191226_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='has_evaluation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='is_validated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submitmeta',
            name='form_field',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='evalbase.SubmitFormField'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreement',
            name='signed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalbase.Signature'),
        ),
    ]
