# Generated by Django 3.0 on 2019-12-31 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0009_auto_20191231_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitmeta',
            name='form_field',
        ),
        migrations.AddField(
            model_name='submitmeta',
            name='form',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='evalbase.SubmitForm'),
            preserve_default=False,
        ),
    ]
