# Generated by Django 3.2.9 on 2021-12-03 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evalbase', '0013_auto_20211123_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='task_interest',
            field=models.ManyToManyField(limit_choices_to=models.Q(('task__conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evalbase.conference'))), to='evalbase.Task'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
