# Generated by Django 4.1.4 on 2022-12-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0016_alter_organization_task_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='sigtext',
            field=models.CharField(default='fooo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='evalbase.conference'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='task_interest',
            field=models.ManyToManyField(to='evalbase.task'),
        ),
    ]
