# Generated by Django 4.1.4 on 2022-12-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0017_signature_sigtext_alter_organization_conference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='longname',
            field=models.CharField(default='the foo agreement', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreement',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
