# Generated by Django 4.1.4 on 2023-11-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0018_agreement_longname_alter_agreement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checker_file',
            field=models.CharField(default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalbase.conference'),
        ),
    ]
