# Generated by Django 5.0 on 2024-02-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0021_alter_submission_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(null=True, blank=True, default=None),
            preserve_default=False,
        ),
    ]
