# Generated by Django 5.0 on 2024-02-28 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0023_alter_task_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='coordinators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
