# Generated by Django 5.0 on 2024-04-09 14:52

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0024_task_coordinators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='coordinators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('shortname'), models.F('conference'), name='case invariant unique pids'),
        ),
    ]
