# Generated by Django 5.0 on 2024-04-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0025_alter_task_coordinators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='added_to_slack',
            field=models.BooleanField(default=False),
        ),
    ]
