# Generated by Django 5.0 on 2024-03-18 15:16

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0025_alter_task_coordinators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('shortname'), models.F('conference'), name='case invariant unique pids'),
        ),
    ]
