# Generated by Django 5.0 on 2024-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0026_userprofile_added_to_slack'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
