# Generated by Django 5.0 on 2024-05-14 18:27

from django.db import migrations

def migrate_track_interest(apps, schema_editor):
    Organization = apps.get_model('evalbase', 'Organization')
    Task = apps.get_model('evalbase', 'Task')
    Track = apps.get_model('evalbase', 'Track')

    for org in Organization.objects.all():
        for task in org.task_interest.all():
            track_name = task.shortname.split('_')[1]
            track = Track.objects.get(shortname=track_name)
            org.track_interest.add(track)
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0028_remove_organization_task_interest_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_track_interest, None),

        migrations.RemoveField(
            model_name='organization',
            name='task_interest',
        ),
        migrations.RemoveField(
            model_name='task',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='task',
            name='coordinators',
        ),
        migrations.RemoveField(
            model_name='task',
            name='url',
        ),

    ]
