# Generated by Django 5.0 on 2024-06-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0029_auto_20240514_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='passphrase',
            field=models.CharField(editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_form', to='evalbase.task'),
        ),
    ]
