# Generated by Django 5.0 on 2024-06-17 21:30

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0030_alter_organization_passphrase_alter_submitform_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='case invariant unique pids',
        ),
        migrations.AlterField(
            model_name='task',
            name='checker_file',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('shortname'), models.F('conference'), name='org_ids_must_be_unique', violation_error_message='Another organization is already using this ID'),
        ),
    ]
