# Generated by Django 5.0 on 2024-06-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0031_remove_organization_case_invariant_unique_pids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitformfield',
            name='help_text',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='submitformfield',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
