# Generated by Django 5.0 on 2024-07-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalbase', '0032_submitformfield_help_text_submitformfield_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='testing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submitformfield',
            name='help_text',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
