# Generated by Django 5.0 on 2024-08-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0033_submitform_testing_alter_submitformfield_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="checker_file",
            field=models.CharField(default="NONE", max_length=500),
        ),
    ]
