# Generated by Django 5.0 on 2024-08-06 13:27

import evalbase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0034_alter_task_checker_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(
                max_length=500, upload_to=evalbase.models.get_submission_path
            ),
        ),
    ]
