# Generated by Django 5.0 on 2024-08-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0035_alter_submission_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="runtag",
            field=models.CharField(max_length=150),
        ),
    ]
