# Generated by Django 5.0 on 2024-08-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0036_alter_submission_runtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submitmeta",
            name="value",
            field=models.CharField(max_length=2500),
        ),
    ]
