# Generated by Django 5.0 on 2024-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0037_alter_submitmeta_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submitformfield",
            name="choices",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="submitformfield",
            name="help_text",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="submitformfield",
            name="meta_key",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="submitformfield",
            name="question",
            field=models.CharField(max_length=250),
        ),
    ]
