# Generated by Django 5.0 on 2024-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0039_alter_submitformfield_choices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submitformfield",
            name="choices",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
