# Generated by Django 5.1.2 on 2024-11-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0043_alter_evaluation_filename_statsfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statsfile",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
