# Generated by Django 5.1.2 on 2024-11-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0046_appendix"),
    ]

    operations = [
        migrations.AddField(
            model_name="appendix",
            name="queryset_field",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="appendix",
            name="queryset_qtype",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="appendix",
            name="queryset_target",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="appendix",
            name="sort_column",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
