# Generated by Django 5.1.2 on 2025-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0047_appendix_queryset_field_appendix_queryset_qtype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="longname",
            field=models.CharField(max_length=150),
        ),
    ]
