# Generated by Django 5.1.2 on 2025-02-18 01:46

from django.db import migrations, models
import django.db.models.deletion

def migrate_conf_links(apps, schema_editor):
    Organization = apps.get_model('evalbase', 'Organization')
    for org in Organization.objects.all():
        org.conf2.add(org.conference)
        org.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0048_alter_conference_longname"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="conf2",
            field=models.ManyToManyField(
                related_name="parts",
                to="evalbase.conference",
            ),
        ),
        
        migrations.RunPython(migrate_conf_links),

        migrations.RemoveConstraint(
            model_name="organization",
            name="org_ids_must_be_unique",
        ),

        migrations.RemoveField(
            model_name='organization',
            name='conference',
        ),

        migrations.RenameField(
            model_name="organization",
            old_name="conf2",
            new_name="conference",
        ),

    ]
