# Generated by Django 5.1.2 on 2025-02-18 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0049_organization_conf2"),
    ]

    operations = []
