# Generated by Django 5.1.2 on 2025-04-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0051_alter_organization_conference"),
    ]

    operations = [
        migrations.AddField(
            model_name="appendix",
            name="average_topic",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
