# Generated by Django 5.2.1 on 2025-05-20 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0052_appendix_average_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="year",
            field=models.IntegerField(
                default=2024,
                validators=[
                    django.core.validators.MinValueValidator(2024),
                    django.core.validators.MaxValueValidator(2032),
                ],
            ),
            preserve_default=False,
        ),
    ]
