# Generated by Django 5.2.1 on 2025-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0053_conference_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="unique_id",
            field=models.CharField(blank=True),
        ),
    ]
