# Generated by Django 5.2.1 on 2025-07-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evalbase", "0054_userprofile_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submitmeta",
            name="key",
            field=models.CharField(max_length=25),
        ),
    ]
